version: '3.7'

services:
  postgres:
    build:
      context: ./postgresdb
    ports:
      - "5432:5432"
    networks:
      - todonetwork
  
  backend:
    image: hse-23-winter:191123
    build:
      context: ./todobackend
    container_name: your-spring-app-container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - todonetwork
    
  frontend:
    build:
      context: ./todofrontend
    ports:
      - "80:80"
    networks:
      - todonetwork
    depends_on:
      - backend

networks:
  todonetwork:
    driver: bridge